import { Grade } from "../../types";

export const grade1: Grade = {
  id: "elementary_grade_1",
  name: "الصف الأول الابتدائي",
  semesters: [
    {
      semesterNumber: 1,
      subjects: [
        // 1. مادة التربية الفنية
        {
          id: "g1_s1_art",
          name: "التربية الفنية",
          slug: "art-g1-s1",
          topics: [
            { id: "g1_s1_art_t1", title: "الوحدة الأولى: مجال الرسم - الموضوع الأول: الألوان ممتعة", pageNumber: 10 },
            { id: "g1_s1_art_t2", title: "الموضوع الثاني: مجموعة الألوان", pageNumber: 16 },
            { id: "g1_s1_art_t3", title: "الموضوع الثالث: الإنسان والرسم", pageNumber: 22 },
            { id: "g1_s1_art_t4", title: "الموضوع الرابع: مدرستي الجميلة", pageNumber: 28 },
            { id: "g1_s1_art_t5", title: "تقويم الوحدة الأولى", pageNumber: 32 },
            { id: "g1_s1_art_t6", title: "الوحدة الثانية : مجال الزخرفة - الموضوع الأول: أزخرف بالمربع والمستطيل", pageNumber: 34 },
            { id: "g1_s1_art_t7", title: "الموضوع الثاني: الزخرفة بالدائرة والمثلث", pageNumber: 40 },
            { id: "g1_s1_art_t8", title: "تقويم الوحدة الثانية", pageNumber: 46 },
            { id: "g1_s1_art_t9", title: "الوحدة الثالثة: مجال الطباعة - الموضوع الأول: أطبع أشكالا من الطبيعة", pageNumber: 48 },
            { id: "g1_s1_art_t10", title: "الموضوع الثاني: أطبع أشكالا بالواني", pageNumber: 52 },
            { id: "g1_s1_art_t11", title: "تقويم الوحدة الثالثة", pageNumber: 56 },
            { id: "g1_s1_art_t12", title: "الوحدة الرابعة : مجال التشكيل المسطح والمجسم - الموضوع الأول: التشكيل بالطين", pageNumber: 58 },
            { id: "g1_s1_art_t13", title: "الموضوع الثاني: أحفورتي الصغيرة", pageNumber: 69 },
            { id: "g1_s1_art_t14", title: "الموضوع الثالث: أسماكي المخططة", pageNumber: 75 },
            { id: "g1_s1_art_t15", title: "تقويم الوحدة الرابعة", pageNumber: 80 },
            { id: "g1_s1_art_t16", title: "فهرس الأشكال التوضيحية واللوحات الفنية", pageNumber: 82 }
          ]
        },

        // 2. مادة التوحيد
        {
          id: "g1_s1_tawheed",
          name: "التوحيد",
          slug: "tawheed-g1-s1",
          topics: [
            { id: "g1_s1_th_t1", title: "الوحدة الأولى: ما يجب على المسلم معرفته - الدرس الأول: ما يجب على المسلم معرفته", pageNumber: 11 },
            { id: "g1_s1_th_t2", title: "الوحدة الثانية : معرفة الله عز وجل - الدرس الثاني: الله الخالق", pageNumber: 18 },
            { id: "g1_s1_th_t3", title: "الدرس الثالث: الله الرزاق", pageNumber: 22 },
            { id: "g1_s1_th_t4", title: "الدرس الرابع: الله الذي ينزل المطر وينبت الزرع", pageNumber: 26 },
            { id: "g1_s1_th_t5", title: "الدرس الخامس: الله المنعم", pageNumber: 29 },
            { id: "g1_s1_th_t6", title: "الدرس السادس: أحب الله", pageNumber: 32 },
            { id: "g1_s1_th_t7", title: "الدرس السابع: أعبد الله", pageNumber: 34 }
          ]
        },

        // 3. مادة الفقه والسلوك
        {
          id: "g1_s1_fiqh",
          name: "الفقه والسلوك",
          slug: "fiqh-g1-s1",
          topics: [
            { id: "g1_s1_fq_t1", title: "الوحدة الأولى : تعظيم القرآن الكريم - الدرس الأول: محبة القرآن الكريم والاستعاذة والبسملة", pageNumber: 40 },
            { id: "g1_s1_fq_t2", title: "الدرس الثاني: العناية بالمصحف", pageNumber: 45 },
            { id: "g1_s1_fq_t3", title: "الوحدة الثانية: سيرة النبي ﷺ - الدرس الثالث: التعريف بالنبي ﷺ", pageNumber: 50 },
            { id: "g1_s1_fq_t4", title: "الدرس الرابع: رحمته ﷺ", pageNumber: 53 },
            { id: "g1_s1_fq_t5", title: "الوحدة الثالثة : السلام - الدرس الخامس: البدء بالسلام", pageNumber: 58 },
            { id: "g1_s1_fq_t6", title: "الدرس السادس: رد السلام", pageNumber: 60 },
            { id: "g1_s1_fq_t7", title: "الوحدة الرابعة: بر الوالدين - الدرس السابع: بر الوالدين", pageNumber: 66 },
            { id: "g1_s1_fq_t8", title: "الدرس الثامن: كيف نبر الوالدين؟", pageNumber: 68 },
            { id: "g1_s1_fq_t9", title: "الوحدة الخامسة : حق المعلم - الدرس التاسع: احترام المعلم", pageNumber: 72 },
            { id: "g1_s1_fq_t10", title: "الوحدة السادسة: آداب قضاء الحاجة - الدرس العاشر: الذكر عند دخول دورة المياه والخروج منها", pageNumber: 78 }
          ]
        },

        // 4. مادة الرياضيات
        {
          id: "g1_s1_math",
          name: "الرياضيات",
          slug: "math-g1-s1",
          topics: [
            { id: "g1_s1_ma_t1", title: "الفصل الأول: المقارنة والتصنيف - التهيئة", pageNumber: 9 },
            { id: "g1_s1_ma_t2", title: "التصنيف وفق خاصية واحدة", pageNumber: 10 },
            { id: "g1_s1_ma_t3", title: "أحل المسألة أمثلها", pageNumber: 13 },
            { id: "g1_s1_ma_t4", title: "التصنيف وفق أكثر من خاصية", pageNumber: 14 },
            { id: "g1_s1_ma_t5", title: "اختبار منتصف الفصل", pageNumber: 16 },
            { id: "g1_s1_ma_t6", title: "مراجعة تراكمية", pageNumber: 17 },
            { id: "g1_s1_ma_t7", title: "يساوي", pageNumber: 18 },
            { id: "g1_s1_ma_t8", title: "أكثر من ، أقل من", pageNumber: 20 },
            { id: "g1_s1_ma_t9", title: "هيا بنا نلعب", pageNumber: 23 },
            { id: "g1_s1_ma_t10", title: "اختبار الفصل", pageNumber: 24 },
            { id: "g1_s1_ma_t11", title: "الاختبار التراكمي", pageNumber: 25 },
            { id: "g1_s1_ma_t12", title: "الفصل الثاني: الأعداد حتى 5 - التهيئة", pageNumber: 27 },
            { id: "g1_s1_ma_t13", title: "الأعداد 1 ، 2، 3", pageNumber: 28 },
            { id: "g1_s1_ma_t14", title: "قراءة الأعداد 1 ، 2 ، 3 ، وكتابتها", pageNumber: 30 },
            { id: "g1_s1_ma_t15", title: "العددان 4 ، 5", pageNumber: 32 },
            { id: "g1_s1_ma_t16", title: "اختبار منتصف الفصل", pageNumber: 34 },
            { id: "g1_s1_ma_t17", title: "مراجعة تراكمية", pageNumber: 35 },
            { id: "g1_s1_ma_t18", title: "قراءة العددين 4 ، 5 ، وكتابتهما", pageNumber: 36 },
            { id: "g1_s1_ma_t19", title: "أحل المسألة أرسم صورة", pageNumber: 38 },
            { id: "g1_s1_ma_t20", title: "قراءة العدد (صفر)، وكتابته", pageNumber: 40 },
            { id: "g1_s1_ma_t21", title: "هيا بنا نلعب", pageNumber: 42 },
            { id: "g1_s1_ma_t22", title: "اختبار الفصل", pageNumber: 43 },
            { id: "g1_s1_ma_t23", title: "الاختبار التراكمي", pageNumber: 44 },
            { id: "g1_s1_ma_t24", title: "الفصل الثالث: الموقع والنمط - التهيئة", pageNumber: 47 },
            { id: "g1_s1_ma_t25", title: "فوق ، تحت", pageNumber: 48 },
            { id: "g1_s1_ma_t26", title: "أعلى ، أوسط ، أسفل", pageNumber: 50 },
            { id: "g1_s1_ma_t27", title: "قبل ، بعد", pageNumber: 52 },
            { id: "g1_s1_ma_t28", title: "اختبار منتصف الفصل", pageNumber: 54 },
            { id: "g1_s1_ma_t29", title: "مراجعة تراكمية", pageNumber: 55 },
            { id: "g1_s1_ma_t30", title: "تحديد الأنماط", pageNumber: 56 },
            { id: "g1_s1_ma_t31", title: "إنشاء الأنماط", pageNumber: 58 },
            { id: "g1_s1_ma_t32", title: "أحل المسألة أبحث عن نمط", pageNumber: 60 },
            { id: "g1_s1_ma_t33", title: "هيا بنا نلعب", pageNumber: 62 },
            { id: "g1_s1_ma_t34", title: "اختبار الفصل", pageNumber: 63 },
            { id: "g1_s1_ma_t35", title: "الاختبار التراكمي", pageNumber: 64 },
            { id: "g1_s1_ma_t36", title: "الفصل الرابع: الأعداد حتى 10 - التهيئة", pageNumber: 67 },
            { id: "g1_s1_ma_t37", title: "الأعداد 6 ، 7 ، 8", pageNumber: 68 },
            { id: "g1_s1_ma_t38", title: "قراءة الأعداد 6 ، 7 ، 8 ، وكتابتها", pageNumber: 70 },
            { id: "g1_s1_ma_t39", title: "العددان 9 ، 10", pageNumber: 72 },
            { id: "g1_s1_ma_t40", title: "قراءة العددين 9 , 10 ، وكتابتهما", pageNumber: 74 },
            { id: "g1_s1_ma_t41", title: "اختبار منتصف الفصل", pageNumber: 76 },
            { id: "g1_s1_ma_t42", title: "مراجعة تراكمية", pageNumber: 77 },
            { id: "g1_s1_ma_t43", title: "أحل المسألة أرسم صورة", pageNumber: 78 },
            { id: "g1_s1_ma_t44", title: "مقارنة الأعداد حتى 10", pageNumber: 80 },
            { id: "g1_s1_ma_t45", title: "ترتيب الأعداد حتى 10", pageNumber: 82 },
            { id: "g1_s1_ma_t46", title: "العدد الترتيبي", pageNumber: 84 },
            { id: "g1_s1_ma_t47", title: "هيا بنا نلعب", pageNumber: 86 },
            { id: "g1_s1_ma_t48", title: "اختبار الفصل", pageNumber: 87 },
            { id: "g1_s1_ma_t49", title: "الاختبار التراكمي", pageNumber: 88 },
            { id: "g1_s1_ma_t50", title: "الفصل الخامس: الأعداد حتى 20 - التهيئة", pageNumber: 91 },
            { id: "g1_s1_ma_t51", title: "العددان 11 ، 12", pageNumber: 92 },
            { id: "g1_s1_ma_t52", title: "الأعداد 13 ، 14 ، 15", pageNumber: 94 },
            { id: "g1_s1_ma_t53", title: "العددان 16 ، 17", pageNumber: 96 },
            { id: "g1_s1_ma_t54", title: "أحل المسألة أبحث عن نمط", pageNumber: 98 },
            { id: "g1_s1_ma_t55", title: "اختبار منتصف الفصل", pageNumber: 100 },
            { id: "g1_s1_ma_t56", title: "مراجعة تراكمية", pageNumber: 101 },
            { id: "g1_s1_ma_t57", title: "الأعداد 18 ، 19 ، 20", pageNumber: 104 },
            { id: "g1_s1_ma_t58", title: "مقارنة الأعداد حتى 20", pageNumber: 106 },
            { id: "g1_s1_ma_t59", title: "ترتيب الأعداد حتى 20", pageNumber: 108 },
            { id: "g1_s1_ma_t60", title: "هيا بنا نلعب", pageNumber: 109 },
            { id: "g1_s1_ma_t61", title: "اختبار الفصل", pageNumber: 110 },
            { id: "g1_s1_ma_t62", title: "الاختبار التراكمي", pageNumber: 111 },
            { id: "g1_s1_ma_t63", title: "الفصل السادس: الجمع - التهيئة", pageNumber: 113 },
            { id: "g1_s1_ma_t64", title: "قصص الجمع", pageNumber: 114 },
            { id: "g1_s1_ma_t65", title: "تمثيل الجمع", pageNumber: 116 },
            { id: "g1_s1_ma_t66", title: "جمل الجمع", pageNumber: 118 },
            { id: "g1_s1_ma_t67", title: "الجمع إلى الصفر", pageNumber: 122 },
            { id: "g1_s1_ma_t68", title: "اختبار منتصف الفصل", pageNumber: 124 },
            { id: "g1_s1_ma_t69", title: "مراجعة تراكمية", pageNumber: 126 },
            { id: "g1_s1_ma_t70", title: "أحل المسألة أمثلها", pageNumber: 128 },
            { id: "g1_s1_ma_t71", title: "تكوين الأعداد : 4 ، 5، 6", pageNumber: 130 },
            { id: "g1_s1_ma_t72", title: "تكوين الأعداد : 7، 8، 9", pageNumber: 132 },
            { id: "g1_s1_ma_t73", title: "تكوين الأعداد: 10 ، 11 ، 12", pageNumber: 134 },
            { id: "g1_s1_ma_t74", title: "الجمع الرأسي", pageNumber: 135 },
            { id: "g1_s1_ma_t75", title: "هيا بنا نلعب", pageNumber: 136 },
            { id: "g1_s1_ma_t76", title: "اختبار الفصل", pageNumber: 137 },
            { id: "g1_s1_ma_t77", title: "الاختبار التراكمي", pageNumber: 138 }
          ]
        },

        // 5. مادة العلوم
        {
          id: "g1_s1_science",
          name: "العلوم",
          slug: "science-g1-s1",
          topics: [
            { id: "g1_s1_sci_t1", title: "تعليمات السلامة", pageNumber: 6 },
            { id: "g1_s1_sci_t2", title: "دليل الأسرة", pageNumber: 7 },
            { id: "g1_s1_sci_t3", title: "الوحدة الأولى : النباتات من حولنا - الفصل الأول : النباتات مخلوقات حية", pageNumber: 9 },
            { id: "g1_s1_sci_t4", title: "الدرس الأول: المخلوقات الحية", pageNumber: 12 },
            { id: "g1_s1_sci_t5", title: "الدرس الثاني : النباتات وأجزاؤها", pageNumber: 14 },
            { id: "g1_s1_sci_t6", title: "العلوم والتقنية والمجتمع : قراءة علمية: زراعة المانجو", pageNumber: 20 },
            { id: "g1_s1_sci_t7", title: "مراجعة الفصل الأول", pageNumber: 21 },
            { id: "g1_s1_sci_t8", title: "الفصل الثاني: النباتات تنمو وتتغير", pageNumber: 25 },
            { id: "g1_s1_sci_t9", title: "الدرس الأول: نمو النباتات", pageNumber: 26 },
            { id: "g1_s1_sci_t10", title: "الدرس الثاني: تعيش النباتات في أماكن كثيرة", pageNumber: 28 },
            { id: "g1_s1_sci_t11", title: "العلوم والرياضيات : بذور متنوعة", pageNumber: 30 },
            { id: "g1_s1_sci_t12", title: "مراجعة الفصل الثاني", pageNumber: 31 },
            { id: "g1_s1_sci_t13", title: "الوحدة الثانية : الحيوانات ومساكنها - الفصل الثالث : الحيوانات من حولنا", pageNumber: 35 },
            { id: "g1_s1_sci_t14", title: "الدرس الأول: انواع الحيوانات", pageNumber: 36 },
            { id: "g1_s1_sci_t15", title: "الدرس الثاني: الحيوانات وحاجاتها", pageNumber: 41 },
            { id: "g1_s1_sci_t16", title: "أعمل كالعلماء: ماذا تأكل الحيوانات؟", pageNumber: 43 },
            { id: "g1_s1_sci_t17", title: "مراجعة الفصل الثالث", pageNumber: 46 },
            { id: "g1_s1_sci_t18", title: "الفصل الرابع: أماكن العيش", pageNumber: 47 },
            { id: "g1_s1_sci_t19", title: "الدرس الأول: مواطن على اليابسة", pageNumber: 48 },
            { id: "g1_s1_sci_t20", title: "الدرس الثاني: مواطن في الماء", pageNumber: 52 },
            { id: "g1_s1_sci_t21", title: "العلوم والرياضيات: أعد الأرجل", pageNumber: 54 },
            { id: "g1_s1_sci_t22", title: "مراجعة الفصل الرابع", pageNumber: 55 },
            { id: "g1_s1_sci_t23", title: "الوحدة الثالثة : أرضنا - الفصل الخامس : موارد الأرض", pageNumber: 56 },
            { id: "g1_s1_sci_t24", title: "الدرس الأول: موارد الأرض", pageNumber: 58 },
            { id: "g1_s1_sci_t25", title: "الدرس الثاني: الاستفادة من موارد الأرض", pageNumber: 60 },
            { id: "g1_s1_sci_t26", title: "الدرس الثالث : المحافظة على موارد الأرض", pageNumber: 64 },
            { id: "g1_s1_sci_t27", title: "العلوم والرياضيات : تدوير العلب المعدنية الفارغة", pageNumber: 66 },
            { id: "g1_s1_sci_t28", title: "مراجعة الفصل الخامس", pageNumber: 67 },
            { id: "g1_s1_sci_t29", title: "مرجعيات الطالب ومصطلحات", pageNumber: 68 }
          ]
        },

        // 6. مادة المهارات الحياتية والأسرية
        {
          id: "g1_s1_life_skills",
          name: "المهارات الحياتية والأسرية",
          slug: "life-skills-g1-s1",
          topics: [
            { id: "g1_s1_ls_t1", title: "دليل الأسرة", pageNumber: 6 },
            { id: "g1_s1_ls_t2", title: "الوحدة الأولى: صحتي وسلامتي - الإمساك بالقلم", pageNumber: 9 },
            { id: "g1_s1_ls_t3", title: "حمل الحقيبة", pageNumber: 17 },
            { id: "g1_s1_ls_t4", title: "الجلوس الصحيح", pageNumber: 24 },
            { id: "g1_s1_ls_t5", title: "الوحدة الثانية: شخصيتي - من أنا ؟", pageNumber: 36 },
            { id: "g1_s1_ls_t6", title: "كيف أتصرف؟", pageNumber: 44 },
            { id: "g1_s1_ls_t7", title: "كيف أعتذر؟", pageNumber: 53 },
            { id: "g1_s1_ls_t8", title: "الوحدة الثالثة: وقتي - أيام الأسبوع", pageNumber: 63 },
            { id: "g1_s1_ls_t9", title: "تمارين عامة", pageNumber: 73 }
          ]
        },

        // 7. مادة الفهارس المشتركة التعليمية
        {
          id: "g1_s1_general_chapters",
          name: "القرآن الكريم والدراسات الإسلامية ولغتي والمواد العامة",
          slug: "general-g1-s1",
          topics: [
            { id: "g1_s1_gen_t1", title: "الوحدة الأولى : القرآن الكريم والدراسات الإسلامية - الدرس الأول: الله ربي", pageNumber: 10 },
            { id: "g1_s1_gen_t2", title: "الدرس الثاني : الإسلام ديني", pageNumber: 12 },
            { id: "g1_s1_gen_t3", title: "الدرس الثالث: محمد نبينا", pageNumber: 16 },
            { id: "g1_s1_gen_t4", title: "الدرس الرابع: القرآن الكريم كتاب الله", pageNumber: 20 },
            { id: "g1_s1_gen_t5", title: "الدرس الخامس: سورة الفاتحة", pageNumber: 24 },
            { id: "g1_s1_gen_t6", title: "الدرس السادس: الله الخالق", pageNumber: 26 },
            { id: "g1_s1_gen_t7", title: "الدرس السابع: سورة الإخلاص", pageNumber: 30 },
            { id: "g1_s1_gen_t8", title: "الدرس الثامن: سورة الفلق", pageNumber: 32 },
            { id: "g1_s1_gen_t9", title: "الدرس التاسع : أركان الإسلام", pageNumber: 36 },
            { id: "g1_s1_gen_t10", title: "الدرس العاشر: الطهارة وإزالة النجاسة", pageNumber: 44 },
            { id: "g1_s1_gen_t11", title: "الدرس الحادي عشر : البدن والملبس", pageNumber: 48 },
            { id: "g1_s1_gen_t12", title: "الدرس الثاني عشر: أسماء الله الحسنى", pageNumber: 52 },
            { id: "g1_s1_gen_t13", title: "الدرس الثالث عشر : سورة الناس", pageNumber: 54 },
            { id: "g1_s1_gen_t14", title: "الوحدة الثانية : لغتي - الدرس الأول : مفردات لغتنا الجميلة", pageNumber: 58 },
            { id: "g1_s1_gen_t15", title: "الدرس الثاني: حرف (ب)", pageNumber: 62 },
            { id: "g1_s1_gen_t16", title: "الدرس الثالث: حرف (ج)", pageNumber: 68 },
            { id: "g1_s1_gen_t17", title: "الدرس الرابع: حرف (ر)", pageNumber: 72 },
            { id: "g1_s1_gen_t18", title: "الدرس الخامس: حرف (س)", pageNumber: 76 },
            { id: "g1_s1_gen_t19", title: "الدرس السادس: اكتب اسمي كاملاً", pageNumber: 82 },
            { id: "g1_s1_gen_t20", title: "الدرس السابع: حرف (ع)", pageNumber: 86 },
            { id: "g1_s1_gen_t21", title: "الدرس الثامن: حرف (ف)", pageNumber: 92 },
            { id: "g1_s1_gen_t22", title: "الدرس التاسع: حرف (و)", pageNumber: 102 },
            { id: "g1_s1_gen_t23", title: "الدرس العاشر: حرف (أ)", pageNumber: 108 },
            { id: "g1_s1_gen_t24", title: "الوحدة الثالثة : الرياضيات - الدرس الأول: الخط المستقيم والمتعرج", pageNumber: 110 },
            { id: "g1_s1_gen_t25", title: "الدرس الثاني: الألوان ( الأحمر الأصفر الأزرق )", pageNumber: 114 },
            { id: "g1_s1_gen_t26", title: "الدرس الثالث: مفهوم قليل وكثير", pageNumber: 118 },
            { id: "g1_s1_gen_t27", title: "الدرس الرابع: مفهوم كبير وصغير", pageNumber: 122 },
            { id: "g1_s1_gen_t28", title: "الدرس الخامس: العدد (1)", pageNumber: 128 },
            { id: "g1_s1_gen_t29", title: "الدرس السادس: الاتجاهان ( يمين - يسار )", pageNumber: 132 },
            { id: "g1_s1_gen_t30", title: "الدرس السابع: مفهوم طويل وقصير", pageNumber: 138 },
            { id: "g1_s1_gen_t31", title: "الدرس الثامن: مفهوم ( خفيف - ثقيل)", pageNumber: 144 },
            { id: "g1_s1_gen_t32", title: "الدرس التاسع: العدد (2)", pageNumber: 150 },
            { id: "g1_s1_gen_t33", title: "الدرس العاشر: مفهوم داخل وخارج", pageNumber: 156 },
            { id: "g1_s1_gen_t34", title: "الدرس الحادي عشر : مفهوم (فوق / أسفل)", pageNumber: 160 },
            { id: "g1_s1_gen_t35", title: "الدرس الثاني عشر : الألوان (أبيض، أخضر، أسود)", pageNumber: 164 },
            { id: "g1_s1_gen_t36", title: "الدرس الثالث عشر : الاتجاهات (أمام / خلف)", pageNumber: 172 },
            { id: "g1_s1_gen_t37", title: "الوحدة الرابعة : العلوم - الدرس الأول: الإنسان", pageNumber: 178 },
            { id: "g1_s1_gen_t38", title: "الدرس الثاني: أجزاء جسم الإنسان", pageNumber: 182 },
            { id: "g1_s1_gen_t39", title: "الدرس الثالث: الحواس الخمس", pageNumber: 186 },
            { id: "g1_s1_gen_t40", title: "الدرس الرابع: الحيوانات وحاجاتها", pageNumber: 188 },
            { id: "g1_s1_gen_t41", title: "الدرس الخامس: انواع الحيوانات", pageNumber: 190 },
            { id: "g1_s1_gen_t42", title: "الدرس السادس: فوائد الحيوانات في حياتنا", pageNumber: 194 },
            { id: "g1_s1_gen_t43", title: "الدرس السابع: النباتات وحاجاتها", pageNumber: 198 },
            { id: "g1_s1_gen_t44", title: "الدرس الثامن: أجزاء النباتات", pageNumber: 202 },
            { id: "g1_s1_gen_t45", title: "الدرس التاسع: فوائد النباتات في حياتنا", pageNumber: 206 },
            { id: "g1_s1_gen_t46", title: "الدرس العاشر: المخلوقات الحية وأنواعها", pageNumber: 208 },
            { id: "g1_s1_gen_t47", title: "الدرس الحادي عشر: حاجات المخلوقات الحية", pageNumber: 212 },
            { id: "g1_s1_gen_t48", title: "الدرس الثاني عشر : خصائص المخلوقات الحية", pageNumber: 214 },
            { id: "g1_s1_gen_t49", title: "الوحدة الخامسة : المهارات الحياتية والأسرية - الدرس الأول: مرافق المدرسة", pageNumber: 218 },
            { id: "g1_s1_gen_t50", title: "الدرس الثاني: البيئة الصفية", pageNumber: 222 },
            { id: "g1_s1_gen_t51", title: "الدرس الثالث: معلومات الطالب الشخصية", pageNumber: 226 },
            { id: "g1_s1_gen_t52", title: "الدرس الرابع: الجلوس الصحيح", pageNumber: 230 },
            { id: "g1_s1_gen_t53", title: "الدرس الخامس: النظافة الشخصية", pageNumber: 234 },
            { id: "g1_s1_gen_t54", title: "الدرس السادس: غسل اليدين والوجه", pageNumber: 240 },
            { id: "g1_s1_gen_t55", title: "الدرس السابع: تنظيف الأسنان", pageNumber: 244 },
            { id: "g1_s1_gen_t56", title: "الدرس الثامن: أنا أحمي نفسي (1)", pageNumber: 252 },
            { id: "g1_s1_gen_t57", title: "الدرس التاسع : أنا أحمي نفسي (2)", pageNumber: 254 },
            { id: "g1_s1_gen_t58", title: "الدرس العاشر: أنا أحمي نفسي (3)", pageNumber: 256 },
            { id: "g1_s1_gen_t59", title: "الدرس الحادي عشر: أنا أحمي نفسي (4)", pageNumber: 258 },
            { id: "g1_s1_gen_t60", title: "الدرس الثاني عشر: آداب الطعام والشراب", pageNumber: 262 },
            { id: "g1_s1_gen_t61", title: "الدرس الثالث عشر : مهارة الأكل باليد - الملعقة", pageNumber: 268 },
            { id: "g1_s1_gen_t62", title: "الدرس الرابع عشر: آداب العطاس", pageNumber: 272 },
            { id: "g1_s1_gen_t63", title: "الدرس الخامس عشر: رسم الخطوط المختلفة", pageNumber: 276 },
            { id: "g1_s1_gen_t64", title: "الدرس السادس عشر : مفهوم الملبس", pageNumber: 280 },
            { id: "g1_s1_gen_t65", title: "الدرس السابع عشر: مفهوم الأسرة", pageNumber: 286 },
            { id: "g1_s1_gen_t66", title: "الدرس الثامن عشر : مفهوم المسكن", pageNumber: 290 },
            { id: "g1_s1_gen_t67", title: "الدرس التاسع عشر: أنا أحمي نفسي 5", pageNumber: 296 },
            { id: "g1_s1_gen_t68", title: "الدرس العشرون: أنا أحمي نفسي 6", pageNumber: 300 },
            { id: "g1_s1_gen_t69", title: "الدرس الواحد والعشرون: أنا أحمي نفسي 7", pageNumber: 304 },
            { id: "g1_s1_gen_t70", title: "الدرس الثاني والعشرون: أنا أحمي نفسي 8", pageNumber: 308 },
            { id: "g1_s1_gen_t71", title: "Unit six: English Language - Lesson one: Greeting (Hi, Bye)", pageNumber: 312 },
            { id: "g1_s1_gen_t72", title: "Lesson two: Numbers (1, 2, 3)", pageNumber: 314 },
            { id: "g1_s1_gen_t73", title: "Lesson three: My family (Father, Mother, Brother)", pageNumber: 322 },
            { id: "g1_s1_gen_t74", title: "Lesson Four: Greeting: (Hi, Bye!)", pageNumber: 328 },
            { id: "g1_s1_gen_t75", title: "Lesson Five: Numbers (4,5,6)", pageNumber: 330 },
            { id: "g1_s1_gen_t76", title: "Lesson Six: My Family: (Sister, Grandfather, Grandmother)", pageNumber: 332 },
            { id: "g1_s1_gen_t77", title: "Lesson Seven: Greeting (Hi,Bye)", pageNumber: 334 },
            { id: "g1_s1_gen_t78", title: "Lesson Eight: Numbers: (1,2,3,4,5,6)", pageNumber: 336 },
            { id: "g1_s1_gen_t79", title: "Lesson Nine: My Family: (Father, Mother, Brother, Sister, Grandfather, Grandmother)", pageNumber: 338 }
          ]
        }
      ]
    },
    {
      semesterNumber: 2,
      subjects: [] // سيتم ملؤها لاحقاً بفهارس الفصل الثاني
    }
  ]
};